version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/img-sharing-mini-project-server
hooks:
  BeforeInstall:
    - location: scripts/before-install.sh
  AfterInstall:
    - location: scripts/install.sh
      runas: ubuntu
      timeout: 300
  ApplicationStart:
    - location: scripts/app-start.sh
      runas: ubuntu
      timeout: 60